spring:
  redis:
    host: localhost
    port: 6379
kafka:
  bootstrap:
    servers: localhost:9092
  messagesInput:
    topic: messagesInput-topic
server:
  port: 9999

delivery:
  redis:
    active-user-key: active-users
