spring:
  redis:
    host: localhost
    port: 6379
kafka:
  consumer-group: "messages-input-group"
  auto-reset-config: "earliest"
  bootstrap:
    servers: localhost:9092
  messagesInput:
    topic: messagesInput-topic
    
server:
  port: 0

headers:
  gateway:
    user-id-forwarded: "X-G-User"
    user-roles-forwarded: "X-G-Roles"

redis:
  disconnect-event-topic: "disconnect-with-token"

ws:
  route:
    get-messages: "/ws/get"
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      
eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
