spring:
  redis:
    host: localhost
    port: 6379
kafka:
  bootstrap:
    servers: localhost:9092
  messagesInput:
    topic: messagesInput-topic
server:
  port: 0

delivery:
  redis:
    active-user-key: active-users
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/   
