spring:
  data:
    mongodb:
      auto-index-creation: true
      host: host.docker.internal
      database: chat-users
      port: ${MONGO_PORT:27017}
    
server:
  port: ${INSTANCE_PORT:43112}
    
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    hostname: host.docker.internal
    leaseRenewalIntervalInSeconds: 5
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
