spring:
  data:
    mongodb:
      auto-index-creation: true
      host: localhost
      database: chat-users
      port: ${MONGO_PORT:27017}
    
server:
  port: ${INSTANCE_PORT:42112}
    
headers:
  gateway:
    user-id-forwarded: "X-G-User"
    user-roles-forwarded: "X-G-Roles"
    user-roles-delimiter: ","
  
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
