spring:
  data:
    cassandra:
      keyspace-name: userkeyspace
      port: 9042
      local-datacenter: datacenter1
      password: cassandra
      username: cassandra
      base-packages: com.example.usersregistrationservice.model
    
server:
  port: ${INSTANCE_PORT:43112}
    
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    hostname: host.docker.internal
    leaseRenewalIntervalInSeconds: 5
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
